-- Seed do banco local (`supabase db reset`).
--
-- Dados de bootstrap que o ambiente REMOTO também precisa — temporada inicial
-- e taxas — não moram aqui: estão em
-- `migrations/20260904120100_bootstrap_data.sql`, porque `seed.sql` não roda
-- em `db push`. As migrations rodam antes deste arquivo no `db reset`, então
-- ele já começa com a Temporada 1 aberta.
--
-- Este arquivo é para dados de conveniência de desenvolvimento, que não devem
-- existir em produção:
--
--   Fase 2  subconjunto de ativos e algumas cotações fixas, para trabalhar na
--           tela de mercado sem depender da brapi
--   Fase 3  usuário de teste com carteira e algumas ordens executadas
--
-- Dados reais de mercado nunca entram aqui — chegam pela Edge Function
-- `sync-quotes`.
